version: "3.9"

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: blog
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./docker/volumes/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - internal

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/servicos/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/html
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      - internal

networks:
  internal:
    driver: bridge
